spring:
    datasource:
        url: jdbc:sqlserver://DESKTOP-5UNLCBQ\SQLEXPRESS;databaseName=spring_social
        username: sa
        password: admin@123
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
        show-sql: true
        hibernate:
          naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
          ddl-auto: update
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 763775490489-944d2qkc2hu8acrvassntecjtln4gi34.apps.googleusercontent.com
              clientSecret: G9QCUlz3fgaSmB_ku6ySRuFL
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
#              clientId: 381050905981594
#              clientSecret: 20b023c0cf407de1fcf85c07ea86e948
              clientId: 2189493027983869
              clientSecret: 02d117dca7b18eda4b0c8e1d5ef547d5
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: d3e47fc2ddd966fa4352
              clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://192.168.15.171:4200/authen-login
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect